name: Build Debian Package

on:
  push:
    branches: [ debian/bookworm ]
  pull_request:
    branches: [ debian/bookworm ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.config.container }}

    strategy:
      matrix:
        config:
          - {name: debian-11-bullseye, container: 'debian:bullseye', distrib: bullseye}
          - {name: debian-12-bookworm, container: 'debian:bookworm', distrib: bookworm}

    steps:
      - run: apt-get -qy update && DEBIAN_FRONTEND=noninteractive apt-get -qy install build-essential debhelper git-buildpackage ppp-dev
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Mark git repository as safe
        run: git config --global --add safe.directory $PWD

      - run: |
          gbp buildpackage -us -uc -nc --git-ignore-branch
          mv ../dcnet-ap*.deb .
          rm dcnet-ap-dbgsym*.deb
          mv dcnet-ap*.deb `basename dcnet-ap*.deb .deb`_${{ matrix.config.distrib }}.deb
      - uses: actions/upload-artifact@v4
        with:
          name: dcnet-ap-${{ matrix.config.distrib }}
          path: "*.deb"
      - run: echo GIT_TAG=`git describe --tags --abbrev=0` >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          files: "*.deb"
